apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "monolithic-mimir.fullname" . }}-config
  labels:
    {{- include "monolithic-mimir.labels" . | nindent 4 }}
data:
  mimir.yaml: |
    {{- tpl .Values.mimir.config . | nindent 4 }}
