{{- if and .Values.s3.accessKeyId (not .Values.s3.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "monolithic-mimir.fullname" . }}-s3
  labels:
    {{- include "monolithic-mimir.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.s3.credentials.accessKeyId.secretKey }}: {{ .Values.s3.accessKeyId | b64enc | quote }}
  {{ .Values.s3.credentials.secretAccessKey.secretKey }}: {{ .Values.s3.secretAccessKey | b64enc | quote }}
{{- end }}
