apiVersion: v1
kind: Service
metadata:
  name: {{ include "monolithic-mimir.fullname" . }}-headless
  labels:
    {{- include "monolithic-mimir.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: {{ .Values.service.memberlistPort }}
      targetPort: memberlist
      protocol: TCP
      name: memberlist
  selector:
    {{- include "monolithic-mimir.selectorLabels" . | nindent 4 }}
