apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "monolithic-mimir.fullname" . }}
  labels:
    {{- include "monolithic-mimir.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "monolithic-mimir.fullname" . }}-headless
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "monolithic-mimir.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "monolithic-mimir.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "monolithic-mimir.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: mimir
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "-config.file=/etc/mimir/mimir.yaml"
            - "-target=all"
            - "-config.expand-env=true"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: grpc
              containerPort: 9095
              protocol: TCP
            - name: memberlist
              containerPort: 7946
              protocol: TCP
          {{- if or .Values.s3.accessKeyId .Values.s3.existingSecret }}
          env:
            - name: {{ .Values.s3.credentials.accessKeyId.envVar }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.s3.existingSecret | default (printf "%s-s3" (include "monolithic-mimir.fullname" .)) }}
                  key: {{ .Values.s3.credentials.accessKeyId.secretKey }}
            - name: {{ .Values.s3.credentials.secretAccessKey.envVar }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.s3.existingSecret | default (printf "%s-s3" (include "monolithic-mimir.fullname" .)) }}
                  key: {{ .Values.s3.credentials.secretAccessKey.secretKey }}
          {{- end }}
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: config
              mountPath: /etc/mimir
              readOnly: true
            - name: data
              mountPath: /data
      volumes:
        - name: config
          configMap:
            name: {{ include "monolithic-mimir.fullname" . }}-config
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        {{- if and .Values.storage.storageClassName (ne .Values.storage.storageClassName "-") }}
        storageClassName: {{ .Values.storage.storageClassName | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.storage.size }}
